microsoft/python-type-stubs

pygame/sprite.pyi
Just a typo, but is making my editor go crazy
=> Fix pygame AbstractGroup attribute typehints

pandas/core/frame.pyi
When specifying `mapper`, you can't specify `index`.
=> Fix mapper-based calling convention of DataFrame rename

pandas/core/reshape/merge.pyi
Closes #60 
Note that the second `merge_asof()` arguments was simply wrong, and that is now fixed.
=> fix arguments for merge

pandas/core/series.pyi
With pylance 2021.5.3, the following code
```python
df = pd.DataFrame({"x": [1.0, 2.0, 3.0], "y": [4.0, 5, 6]})
sx: pd.Series = df["x"]
ss = sx.astype(str)
print(ss)
```
reports on the `astype` line:
```
Argument of type "Type[str]" cannot be assigned to parameter "dtype" of type "Dtype@__getitem__ | str" in function "astype"
  Type "Type[str]" cannot be assigned to type "Dtype@__getitem__ | str"
    Type "Type[str]" cannot be assigned to type "Dtype@__getitem__"
    "Type[type]" is incompatible with "_str"
```
This PR fixes that issue.
=> fix series.astype dtype argument for pandas

pandas/core/series.pyi
pyright 2021.5.3
The following simple code reports an error:
```python
s = pd.Series([1, 2, 3], name="hey")
t = pd.Series([1, 2, 3], name=s.name)
```
Error is:
```
Argument of type "Hashable | None" cannot be assigned to parameter "name" of type "_str" in function "__init__"
  Type "Hashable | None" cannot be assigned to type "_str"
    "Hashable" is incompatible with "str"
    Type "None" cannot be assigned to type "_str"
```
This PR fixes this by changing the argument type for `name` in `Series` to be `Optional[Hashable]`
=> pandas:  fix series name argument

matplotlib/axes/_axes.pyi, matplotlib/image.pyi
There was a comma missing after `self`.
Also, my type checker had problems with circular imports in `matplotlib/image.pyi` which I was able to solve by making the import more specific. I can remove that change if you'd prefer that.
=> Fix a syntax error in the matplotlib stubs

pandas/core/series.pyi
pylance 2021.6.3
This simple code 
```python
s = pd.Series(4)
```
produces the error:
```
Argument of type "Literal[4]" cannot be assigned to parameter "data" of type "ndarray | Dict[_str, ndarray] | Sequence[Unknown] | Index[Unknown] | Series[S1@Series] | Dict[int, S1@Series] | Dict[_str, S1@Series] | None" in function "__init__"
  Type "Literal[4]" cannot be assigned to type "ndarray | Dict[_str, ndarray] | Sequence[Unknown] | Index[Unknown] | Series[S1@Series] | Dict[int, S1@Series] | Dict[_str, S1@Series] | None"
    "Literal[4]" is incompatible with "ndarray"
    "Literal[4]" is incompatible with "Dict[_str, ndarray]"
    "Literal[4]" is incompatible with "Sequence[Unknown]"
    "Literal[4]" is incompatible with "Index[Unknown]"
    "Literal[4]" is incompatible …
```
=> Allow a scalar argument for data in Series

pandas/core/series.pyi
pylance 2021.7.3
Following code:
```python
import numpy as np
df: pd.DataFrame = pd.DataFrame({"x": [1, np.nan, 3]})
df["x"].fillna(1234)
```
produces
```
No overloads for "fillna" match the provided arguments
  Argument types: (Literal[1234])
```
This PR fixes that issue.
=> pandas: allow scalars as args to series.fillna

pandas/core/frame.pyi
pylance 2021.7.5
```python
df = pd.DataFrame(
[[1, 10], [2, 20], [3, 30]], columns=["one", "ten"], index=["a", "b", "c"]
)
i = pd.Index(["a", "c"])
df.loc[i, "ten"] = 100
```
produces
```
Argument of type "tuple[Index[str], str]" cannot be assigned to parameter "idx" of type "Series[bool] | np_ndarray_bool | Sequence[bool] | str | str_ | Tuple[Series[bool] | np_ndarray_bool | Sequence[bool] | slice | np_ndarray_int64 | Index[int] | List[int] | Series[int] | List[str], Series[bool] | np_ndarray_bool | Sequence[bool] | List[str] | str | str_]" in function "__setitem__"
  Type "tuple[Index[str], str]" cannot be assigned to type "Series[bool] | np_ndarray_bool | Sequence[bool] | str | str_ | Tuple[Series[bool] | np_ndarray_bool | Sequence[bool] | slice …
```
=> allow Index in setitem on DataFrame

cv2/__init__.pyi
future PR's still need to fix
variable value assignments
add `#incomplete` to functions
add actual types
=> initial opencv scraped stub

pandas/io/html.pyi
In the documentation, it's [stated](https://pandas.pydata.org/docs/reference/api/pandas.read_html.html#pandas.read_html) that the usage of the `parse_dates` argument of the `pandas.read_html` function should follow that of the `pandas.read_csv` function. From the [documentation of the `parse_dates` argument of the `pandas.read_csv` function](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv), it can take either a "bool or list of int or names or list of lists or dict".
=> Fix annotation for the `parse_dates` argument of the `pandas.read_html` function

matplotlib/patches.pyi
Patch and its subclasses accept arguments to `__init__`.
Add `*args` and `**kwargs` to suppress false positive errors when instantiating patches.
=> matplotlib Patch.__init__ accepts any arguments

pandas/core/frame.pyi
pylance 2021.8.2
```python
df = pd.DataFrame([[1, "Y"], [2, "N"]], columns=["n", "f"])
df.loc[df.n >= 1, "f"] = "foo"
```
produces
```
Argument of type "Literal['foo']" cannot be assigned to parameter "value" of type "float | ndarray | Series[Dtype@__setitem__] | DataFrame" in function "__setitem__"
  Type "Literal['foo']" cannot be assigned to type "float | ndarray | Series[Dtype@__setitem__] | DataFrame"
    "Literal['foo']" is incompatible with "float"
    "Literal['foo']" is incompatible with "ndarray"
    "Literal['foo']" is incompatible with "Series[Dtype@__setitem__]"
    "Literal['foo']" is incompatible with "DataFrame"
```
This PR fixes that issue.
=> pandas: fix .loc setitem with a scalar

pandas/core/series.pyi
pylance 2021.8.2
```python
df = pd.DataFrame([[1, "Y"], [2, "N"]], columns=["n", "flag"])
s = df["flag"]
s2 = df["n"].mask(s == "Y", 0)
```
reports
```
Argument of type "Series[_bool]" cannot be assigned to parameter "cond" of type "Series[Dtype@__getitem__] | ndarray | (*args: Unknown, **kwargs: Unknown) -> Unknown" in function "mask"
  Type "Series[_bool]" cannot be assigned to type "Series[Dtype@__getitem__] | ndarray | (*args: Unknown, **kwargs: Unknown) -> Unknown"
    TypeVar "S1@Series" is invariant
      Type "_bool" cannot be assigned to type "Dtype@__getitem__"
    "Series[_bool]" is incompatible with "ndarray"
    Type "Series[_bool]" cannot be assigned to type "(*args: Unknown, **kwargs: Unknown) -> Unknown"
```
This PR fixes that issue.
=> fix Series.mask argument

pandas/core/tools/datetimes.pyi
pylance V2021.10.0
```python
s = pd.Series(["10/05/2020", "10/06/2020"])
dt: pd.Series = pd.to_datetime(s)
print(dt)
df = pd.DataFrame([[10, 5, 2020], [10, 6, 2020]], columns=["month", "day", "year"])
dft: pd.Series = pd.to_datetime(df)
print(dft)
```
reports
```
No overloads for "to_datetime" match the provided arguments
  Argument types: (Series[Unknown])
```
on the first assignment (`dt = ...`)  This PR fixes that.
=> Allow Series as argument to pandas.to_datetime

pandas/core/frame.pyi
I believe this fixes #45, which pointed out that [DataFrame.groupby](https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.groupby.html) now (since pandas v1.1) accepts a `dropna` argument.
This is my first time contributing, and it doesn't look like there's any kind of automated testing I can run to check this or add a new test case (if there is, please let me know!). Instead, I created this tiny snippet in a fresh environment (py3.10, installed pandas, cloned this repo into the dir `typings`). 
```
df = pd.DataFrame()
df.groupby("x", dropna=False)
```
Without the change, I get `No parameter named "dropna"` from Pylance, as described in #45. With it, the code type checks as expected.
It's also not clear to me how this change would interact with …
=> pandas: add dropna argument to DataFrameGroupBy

pandas/io/parsers.pyi
pylance 2022.1
```python
df = pd.read_csv(
"s3://mybucket", on_bad_lines="warn", storage_options={"myawskey": "fake"}
)
```
produces the error:
```
No overloads for "read_csv" match the provided arguments
  Argument types: (Literal['s3://mybucket'], Literal['warn'], dict[str, str])
```
This PR fixes this.  These were changes made in pandas 1.2 and pandas 1.3.
=> read_csv on_bad_lines and storage_options arguments

matplotlib/axes/_axes.pyi, matplotlib/lines.pyi, matplotlib/pyplot.pyi
My VSCode Pylance told me I couldn't pass `marker="P"` into `matplotlib.pyplot.scatter`.  Am I right in thinking this is the place to correct that?  While I was there I checked where else the `MarkerStyle` was specified in these stubs.
Relevant matplotlib docs:
[Axes.scatter](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.scatter.html?highlight=scatter#matplotlib.axes.Axes.scatter)
[pyplot.scatter](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html?highlight=scatter#matplotlib.pyplot.scatter)
[Line2D](https://matplotlib.org/stable/api/_as_gen/matplotlib.lines.Line2D.html?highlight=line2d#matplotlib.lines.Line2D)
=> Matplotlib marker types

pandas/io/parsers.pyi
pylance 2022.2.0
The following code reports errors incorrectly:
```python
from io import StringIO
from pandas.io.parsers import TextFileReader
dio = StringIO("a,b\n 1,2\n 3,4\n")
df: pd.DataFrame = pd.read_csv(dio)
print(df)
dio.seek(0)
tr: pd.DataFrame = pd.read_csv(dio)
dio.seek(0)
tr2: TextFileReader = pd.read_csv(dio, iterator=True)
dio.seek(0)
tr3: pd.DataFrame = pd.read_csv(dio, iterator=False)
dio.seek(0)
tr5: TextFileReader = pd.read_csv(dio, chunksize=10)
dio.seek(0)
tr6: pd.DataFrame = pd.read_csv(dio, chunksize=None)
dio.seek(0)
tr7: pd.DataFrame = pd.read_csv(dio, header="infer")
dio.seek(0)
tr8: TextFileReader = pd.read_csv(dio, header="infer", iterator=True)
ftr1: TextFileReader = pd.read_csv("hey.csv")
ftr2: pd.DataFrame = pd.read_csv("hey.csv", …
```
=> fix read_csv to work with different overloads

pandas/core/reshape/merge.pyi
pylance 2022.2.0
```python
df1 = pd.DataFrame([["a", 1], ["b", 2]], columns=["let", "num"]).set_index("let")
s2 = df1["num"]
res = pd.merge(s2, df1, left_index=True, right_index=True)
print(res)
```
reports
```
Argument of type "Series[S1@__getitem__]" cannot be assigned to parameter "left" of type "DataFrame" in function "merge"
  "Series[S1@__getitem__]" is incompatible with "DataFrame"
```
This PR fixes that issue.  Note it was previously fixed in #61 and then broken in #129 .
=> fix arguments to pandas pd.merge

partial/pandas/_typing.pyi, partial/pandas/core/frame.pyi, tests/pandas/test_frame.py
Allow `DataFrame.iloc` to accept lists, etc. that produce a `DataFrame`
=> pandas: fix iloc to accept list

matplotlib/pyplot.pyi
Adds overloads to plt.subplots().
The overloads handle, in order:
1. `plt.subplots(nrows=1, nrows=2, squeeze=True)` -> single `Axes` (the default case)
2. `plt.subplots(squeeze=False) -> ndarray` (explicit array return, as keyword)
3. `plt.subplots(nrows, ncols, sharex, sharey, False) -> ndarray` (explicit array return, as positional)
4. `plot.subplots(nrows, ncols) -> ndarray | Axes` (not knowable at compile time)
The current return value is incorrect, and a big stumbling block when dealing with multi-Axes plots.
=> matplotlib.pyplot.subplots: Add multi-plot overloads

matplotlib/axes/_base.pyi
in the code the `__getitem__` call is  really on the parent class
https://github.com/matplotlib/matplotlib/blob/1efc391434812f0f24392ca4a45c5cd846f46862/lib/matplotlib/axes/_base.py#L1378
https://github.com/microsoft/pylance-release/issues/3192
=> adding missing `__getitem__` to matplot _AxesBase

matplotlib/pyplot.pyi
=> Fix return type on matplotlib.pyplot.subplot_mosaic

sklearn/datasets/_openml.pyi
```python
from sklearn.datasets import fetch_openml
survey = fetch_openml(data_id=534, as_frame=True)
```
the docstring  ` (data, target) : tuple if ``return_X_y`` is True`
```
Returns
-------
data : :class:`~sklearn.utils.Bunch`
Dictionary-like object, with the following attributes.
data : np.array, scipy.sparse.csr_matrix of floats, or pandas DataFrame
The feature matrix. Categorical features are encoded as ordinals.
target : np.array, pandas Series or DataFrame
The regression target or classification labels, if applicable.
Dtype is float if numeric, and object if categorical. If
``as_frame`` is True, ``target`` is a pandas object.
DESCR : str
The full description of the dataset.
feature_names : list
The names of the dataset columns.
target_names: list
The names of the target columns. …
```
=> adding sklearn overload for fetch_openml

matplotlib/pyplot.pyi
https://github.com/microsoft/pylance-release/issues/3482
Expect `plt.subplots(1)` to return just a single Axes
```python
from matplotlib import pyplot as plt
fig, ax = plt.subplots(1)
ax.get_xaxis().set_ticks([])
```
=> Update matplot subplots stubs

matplotlib/figure.pyi
Modification to support situation when `subplots` receives no argument and returns a singe `Axes`. 
The third `@overload` should be used, but it was using the 4th overload due to the defaults in `nrows` and `ncols` when `squeeze` is not given. This PR corrects that.
=> Support to `subplots` receiving no argument

matplotlib/widgets.pyi
Fixes https://github.com/microsoft/python-type-stubs/issues/268
I did a quick scan of the other matplotlib stub files and didn't see any other issues of this sort.
=> Remove import from same file

stubs/sklearn/metrics/_regression.pyi
Instead, two `@deprecated` overloads were added with helpful messages to specify that only `squared` is deprecated.
Resolves #318.
=> Unmark `sklearn.metrics.mean_squared_error` and `mean_squared_log_error` as deprecated

.gitignore, README.md, pyproject.toml
=> Make stubs installable from github

.github/workflows/test.yml
Currently the `test` action is failing with the following error:
```Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: v2`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down```
The [actions/cache docs](https://github.com/actions/cache?tab=readme-ov-file#%EF%B8%8F-important-changes) state that support for v2 ended on February 1, 2025.
=> Upgrade to actions/cache@v4

pyproject.toml, stubs/sklearn/preprocessing/_data.pyi
Not only can overloads differ between pyright and mypy, but in this case, mypy was completely wrong in `tests/sklearn/preprocessing_tests.py`.
`assert_type` is only used in static type tests, and those tests are mostly used to confirm complex type results (from overloads and typevars). At that point may as well just disable it.
I don't see this as an issue in the idea of "porting to typeshed" either, because typeshed already deals with typecheckers differences in tests. And would have to adapt to its repo.
=> Add reason to ignore mypy assert-type in tests
